accordion/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import Index

app_name = 'message'

urlpatterns = [
    path('', Index, name= 'Index'),
]

story8/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('accordion.urls')),
    path('story9/', include('story9.urls')),
]

story9/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import Index, search, top5_url, addLike_url

app_name = 'story9'

urlpatterns = [
    path('', Index, name= 'Index'),
    path('search', search, name='books_data'),
    path('addLike_url', addLike_url, name = 'addLike_url'),
    path('top5_url', top5_url, name='top5_url')
]

accordion/models.py
from django.db import models

# Create your models here.

story9/models.py
from django.db import models

# Create your models here.
class Book(models.Model):
    id = models.CharField(max_length=130, primary_key=True)
    cover = models.CharField(max_length=400)
    title = models.CharField(max_length=200)
    author = models.CharField(max_length=200, blank=True)
    like = models.IntegerField(default=0)

accordion/views.py
from django.shortcuts import render, redirect

# Create your views here.

def Index(request):
    return render(request, 'story8.html')

story9/views.py
from django.shortcuts import render
from django.http import JsonResponse
import json
import requests
from .models import Book
from django.views.decorators.csrf import csrf_exempt


# Create your views here.
def Index(request):
    return render(request,'story9.html')

def search(request):
    try:
        q = request.GET['q']
    except:
        q = "quilting"

    json_response= request.get("https://www.googleapis.com/books/v1/volumes?q=" + q).json()
    for i in json_response['items']:
        try:
            data_book = Book.objects.get(id=i['id'])
            like = data_book.like
        except:
            like = 0
        i['volumeInfo']['like'] = like

    return JsonResponse(json_response)

@csrf_exempt
def addLike_url(request):
    data_book, created = Book.objects.get_or_create(
        id=request.POST['id'],
        cover=request.POST['cover'],
        title=request.POST['title'],
        author=request.POST['author'],
        like=request.POST['like']
    )
    data_book.save()
    return JsonResponse(data_book.like, safe=False)

def top5_url(request):
    data_book_sort= Book.objects.order_by('-like')[:5]
    top5_list=[]
    for i in data_book_sort:
        top5_list.append({
            'id' : i.id,
            'cover': i.cover,
            'title': i.title,
            'author':i.author,
            'like': i.like
        })
    data={
        'top5_list' : top5_list,
    }
    return JsonResponse(data,safe=False)

accordion/templates/story8.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <title>Hello</title>
    <meta charset="utf-8">
    <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}">
    <script src="{% static 'jquery-3.5.0.min.js' %}"></script>
    <!-- To ensure proper rendering and touch zooming in Mobile Phones -->
    <meta name="viewport" content="width=device-width, initial-scale=1">

</head>
<body>

<div class="container">

<ul class="ul_accordion" style="list-style: none;">
    <li>
        <a onclick="up()" class="myButton">u</a> <a onclick="down()" class="myButton">d</a>

        <!--        <button  onclick="up()" type="button" class="up_button">up</button> <button onclick="down()" type="button" class="down_button">down</button>-->
        <button class="accordion">ABOUT ME</button>
        <div class="panel">
            <p>Hello, my name is Nikita Jacey, I’m a student that currently enrolled at the University of Indonesia majoring in System Information class of 2023.
            </p>
        </div>

    </li>
    <li>
        <a onclick="up()" class="myButton">u</a> <a onclick="down()" class="myButton">d</a>

        <button class="accordion">EXPERIENCES</button>
        <div class="panel">
            <p>I have a lot of interest on creative field especially in design. I can operate Adobe Photoshop and sometimes Adobe Illustrator.
            Some of my experiences in college:
            member of Campaign Division in PEMIRA Fasilkom UI 2019, member of Futsal Planner in PERAK Fasilkom UI 2020, and HRD of DNC COMPFEST 12.</p>
        </div>
    </li>
        <li>
            <a onclick="up()" class="myButton">u</a> <a onclick="down()" class="myButton">d</a>
            <button class="accordion">CONTACT</button>
        <div class="panel">
            <p>You can contact me through email: Nikita17jacey@gmail.com.</p>
        </div>
        </li>
    <li>
        <a onclick="up()" class="myButton">u</a> <a onclick="down()" class="myButton">d</a>

        <button class="accordion">JUKE BOX</button>
        <div class="panel" style="padding: 0 0;">

        <ul id="juke">
            <li></li>
                <li><a href="https://open.spotify.com/track/7kQkmyoHCEqwe7QwDbkSXM" target="_blank"><img src="{% static 'finneas.jpg' %}"></a></li>
                <li><a href="https://open.spotify.com/track/09bEFRkwyd648AXubqQxir" target="_blank"><img src="{% static 'summumbonum.jpg' %}"></a> </li>
                <li><a href="https://open.spotify.com/track/1dMmkgiggnLUnlvRKZoBWG" target="_blank"><img src="{% static 'utha.jpg' %}"></a> </li>
                <li><a href="https://open.spotify.com/track/3AJwUDP919kvQ9QcozQPxg" target="_blank"><img src="{% static 'yellow.jpg' %}"></li></a>
                follow me on Spotify: nktjcy
        </ul>
            <br>
        </div>
    </li>
</ul>
    <br>
    <section id="header">
        <h1><b>U: Up</b></h1>
        <h1><b>D: Down</b></h1>
    </section>
    <p><i>Story 8</i> &copy; 2020 Nikita Jacey.<p>
    <h4><a href="{% url 'story9:Index' %}"> >Story 9 </a></h4>

</div>


<script type="text/javascript">
		var acc = document.getElementsByClassName("accordion");
		var i;

		for (i = 0; i < acc.length; i++) {
		  acc[i].addEventListener("click", function() {
		    this.classList.toggle("active");
		    var panel = this.nextElementSibling;
		    if (panel.style.maxHeight){
		      panel.style.maxHeight = null;
		    } else {
		      panel.style.maxHeight = panel.scrollHeight + "px";
		    }
		  });
		}

		function up(){
		var list = document.querySelector(".ul_accordion");
            list.insertBefore(event.currentTarget.parentNode,(event.currentTarget.parentNode).previousElementSibling);
            }

        function down(){
        var list = document.querySelector(".ul_accordion");
            list.insertBefore((event.currentTarget.parentNode).nextElementSibling,event.currentTarget.parentNode);
        }
</script>
</body>
</html>

story9/templates/story9.html
{% load static %}
<html lang="en">
<head>
    <title>BOOOOOKS</title>
    <meta charset="utf-8">
    <link rel="stylesheet" type="text/css" href="{% static 'story9.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'top5.css' %}">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script>
      const addLike_url = "{% url 'story9:addLike_url' %}";

      const top5_url = "{% url 'story9:top5_url' %}";
    </script>
</head>
<body>


<div class="container">
    <div class="card-header">
        <p style="text-align: center;"><i>Story 9</i> &copy; 2020 Nikita Jacey.</p>
    <h4><a href="{% url 'message:Index' %}">< back</a></h4>
    <div class ="input-class">
        <h1>SEARCH</h1>
        <h1>BOOKS</h1>
            <input id="keyword" type="type" placeholder="Search...">
            <button type="submit" id="submit">search</button>
    </div>
        <br>
        <a id="show">Show Top 5 Books</a>

    </div>

    <div class="card-body">
        <div id="top5"> </div>

        <div id="before" style="font-weight: bold;">
            Search your books here!
        </div>
        <ul id="result"></ul>
    </div>
    </div>
<script src="{% static 'jquery-3.5.0.min.js' %}"></script>
<script src="{% static 'story9.js' %}"></script>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.min.js" type="text/javascript"></script>


</body>
</html>